spring.application.name=historial-clinico-backend
server.port=8080
spring.profiles.active=dev
 
spring.jpa.properties.hibernate.format_sql=true
spring.jackson.serialization.write-dates-as-timestamps=false